version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: healthcarepoc
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Consis10C!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Flask Application
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=healthcarepoc
      - DB_USER=postgres
      - DB_PASSWORD=Consis10C!
      - JAVA_HOME=C:\Program Files\Java\jdk-1.8\jdk-1.8
      - PATH=C:\Program Files\Java\jdk-1.8\jdk-1.8\bin;%PATH%
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./downloads:/app/downloads

volumes:
  postgres_data: 